[format]
delim = "  "
workspace = "{id} {clients} {delim}"
client = "{icon}"
#client_active = "{icon}"
client_active = "<span color='red'>{icon}</span>"

[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = ""
"kitty" = ""
"firefox" = ""
"code-oss" = "󰨞"
"VSCodium" = "󰨞"
"org.pwmt.zathura" = ""
"thunar" = ""
"Webcord" = "󰙯"
"com.obsproject.Studio" = "󰻂"
"spotify" = ""
"Gimp-2.10" = ""
"libreoffice-writer" = ""
"obsidian" = "󱞁"
"steam" = ""
"virt-manager" = ""
"vlc" = ""

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
rofi = "Search"

